# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'David Reed'
tagline:             ''
description:         ''
url:                 http://www.ktema.org
baseurl:             https://davidmreed.github.io
paginate:            5

# About/contact
author:
  name:              David Reed
  url:               http://www.ktema.org
  email:             david@ktema.org

# Custom vars
version:             1.0.0
